ALL: lxcstart

CC = gcc
CFLAGS = -Wall -Werror -I/usr/local/include/libct -g -Wall -Werror
LDFLAGS = -g -Wl,--no-as-needed -L/usr/local/lib -lnl-route-3 -lnl-3 -L/usr/local/lib/x86_64-linux-gnu -lct -ldbus-1 -lselinux -lapparmor
